[package]
name = "rsfind"
version = "0.1.0"
authors = ["Cary Clark <clarkcb@gmail.com>"]
edition = "2024"

[dependencies]
chrono = "0.4.42"
regex = "1.12.2"
serde = { version ="1.0.228", features = ["derive"] }
serde_json = "1.0.145"
once_cell = "1.21.3"
sqlite = "0.36.0"
#zip = "2.5.0"
