name: dartfind
description: A sample command-line application.
# version: 1.0.0
# homepage: https://github.com/clarkcb/xfind
# repository: https://github.com/clarkcb/xfind

environment:
  sdk: '>=2.19.0 <3.11.0'

dependencies:
  path: ^1.9.1
  sqlite3: ^2.4.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
